--Erro: Todos alias usado na música deve ser especificado
tom: G
escala: m
compasso: 16

#PREUM : 
[G5, *, F5, *, G5, *, -, G5, *, -, F5, *, G5, *, -, D6]
[-, -, F6, *, D6, *, -, C6, -, C6, -, C6, D6, *, A#5, *]
[G5, *, F5, *, G5, *, -, G5, *, -, F5, *, D6, *, -, C6]

#VARUM : 
[-, -, A#5, -, C6, *, -, A5, -, A5, -, A5, A#5, *, A5, *]

#VARDOIS : 
[-, -, A#5, -, C6, *, D6, A5, -, A5, -, A5, A#5, *, A5, *]

PREUM
VARUM
PREDOIS
VARDOIS
